/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.*;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Earl Appiah - eea7
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    //for the mennu selection
    boolean boolMenu = true;
    boolean boolHome = false;
    boolean boolUser = false;
    boolean boolReserve = false;
    boolean boolCalendar = false;
    boolean boolMyTickets = false;
    boolean boolOther = false;
    //sql database
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    //User details
    String id = "";
    String username = "";
    String fullname = "";
    String email = "";
    String dob = "";
    String number = "";

    public Main() {
        initComponents();
        Connect();
        LoadStartPlace();
        LoadDestination();
        buttonhidemenuMouseClicked(null);
        // Main panel set-up
        welcomePanel.setVisible(true);
        reserveTicketPanel.setVisible(false);
        myTicketsPanel.setVisible(false);
        calendarPanel.setVisible(false);
        profilePanel.setVisible(false);
        shadowPanel.setBackground(new Color(0, 0, 0, 100));
        txtNumTickets.setEnabled(false);
        reserveButton.setEnabled(false);
        
        //setting user details
        id = login.getId();
        username = login.getUsername();
        fullname = login.getFullname();
        email = login.getEmail();
        dob = login.getDob();
        number = login.getNumber();
        setProfile();
        getMyTicketsDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        iconMinMaxClose = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        buttonMax = new javax.swing.JPanel();
        buttonMin = new javax.swing.JPanel();
        accountN = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        lineHideMenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        lineHome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        userButton = new javax.swing.JLabel();
        lineUser = new javax.swing.JPanel();
        nextLine = new javax.swing.JPanel();
        menuHide = new javax.swing.JPanel();
        menuButtons = new javax.swing.JPanel();
        reserve = new javax.swing.JPanel();
        reserveTicketButton = new javax.swing.JLabel();
        tickets = new javax.swing.JPanel();
        myTicketsButton = new javax.swing.JLabel();
        calendar = new javax.swing.JPanel();
        calendarButton = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        welcomeLabel1 = new javax.swing.JLabel();
        welcomeImage = new javax.swing.JLabel();
        shadowPanel = new javax.swing.JPanel();
        reserveTicketPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        reserveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtStartPlace = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtTrainNo = new javax.swing.JLabel();
        txtTrainName = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNumTickets = new javax.swing.JTextField();
        myTicketsPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        profilePanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(1066, 50));
        Header.setLayout(new java.awt.BorderLayout());

        iconMinMaxClose.setBackground(new java.awt.Color(153, 153, 153));
        iconMinMaxClose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconMinMaxClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClose.setBackground(new java.awt.Color(102, 102, 102));
        buttonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Railway/images/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        buttonClose.add(close, java.awt.BorderLayout.CENTER);

        iconMinMaxClose.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        buttonMax.setBackground(new java.awt.Color(102, 102, 102));
        buttonMax.setLayout(new java.awt.BorderLayout());
        iconMinMaxClose.add(buttonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        buttonMin.setBackground(new java.awt.Color(102, 102, 102));
        buttonMin.setLayout(new java.awt.BorderLayout());
        iconMinMaxClose.add(buttonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(iconMinMaxClose, java.awt.BorderLayout.LINE_END);

        accountN.setBackground(new java.awt.Color(102, 102, 102));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("   ID Number: \"idenfier string\"");

        javax.swing.GroupLayout accountNLayout = new javax.swing.GroupLayout(accountN);
        accountN.setLayout(accountNLayout);
        accountNLayout.setHorizontalGroup(
            accountNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountNLayout.createSequentialGroup()
                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountNLayout.setVerticalGroup(
            accountNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Header.add(accountN, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setAutoscrolls(true);
        Menu.setMinimumSize(new java.awt.Dimension(200, 100));
        Menu.setPreferredSize(new java.awt.Dimension(270, 100));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(102, 102, 102));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 658));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineHideMenu.setBackground(new java.awt.Color(102, 102, 102));
        lineHideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHideMenuLayout = new javax.swing.GroupLayout(lineHideMenu);
        lineHideMenu.setLayout(lineHideMenuLayout);
        lineHideMenuLayout.setHorizontalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineHideMenuLayout.setVerticalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineHideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        hideMenu.setBackground(new java.awt.Color(204, 204, 204));
        hideMenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Railway/images/back_32px.png"))); // NOI18N
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        hideMenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        lineHome.setBackground(new java.awt.Color(102, 102, 102));
        lineHome.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHomeLayout = new javax.swing.GroupLayout(lineHome);
        lineHome.setLayout(lineHomeLayout);
        lineHomeLayout.setHorizontalGroup(
            lineHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineHomeLayout.setVerticalGroup(
            lineHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, -1));

        home.setBackground(new java.awt.Color(102, 102, 102));
        home.setLayout(new java.awt.BorderLayout());

        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Railway/images/home_32px.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        home.add(homeButton, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 50, 50));

        user.setBackground(new java.awt.Color(102, 102, 102));
        user.setLayout(new java.awt.BorderLayout());

        userButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Railway/images/customer_32px.png"))); // NOI18N
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
        });
        user.add(userButton, java.awt.BorderLayout.CENTER);

        MenuIcon.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        lineUser.setBackground(new java.awt.Color(102, 102, 102));
        lineUser.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineUserLayout = new javax.swing.GroupLayout(lineUser);
        lineUser.setLayout(lineUserLayout);
        lineUserLayout.setHorizontalGroup(
            lineUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineUserLayout.setVerticalGroup(
            lineUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        nextLine.setBackground(new java.awt.Color(102, 102, 102));
        nextLine.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout nextLineLayout = new javax.swing.GroupLayout(nextLine);
        nextLine.setLayout(nextLineLayout);
        nextLineLayout.setHorizontalGroup(
            nextLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        nextLineLayout.setVerticalGroup(
            nextLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(nextLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, -1));

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuHide.setBackground(new java.awt.Color(204, 204, 204));
        menuHide.setPreferredSize(new java.awt.Dimension(220, 549));

        menuButtons.setBackground(new java.awt.Color(255, 255, 255));

        reserve.setLayout(new java.awt.BorderLayout());

        reserveTicketButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        reserveTicketButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reserveTicketButton.setText("Reserve Ticket");
        reserveTicketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reserveTicketButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reserveTicketButton.setPreferredSize(new java.awt.Dimension(200, 100));
        reserveTicketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveTicketButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reserveTicketButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reserveTicketButtonMouseExited(evt);
            }
        });
        reserve.add(reserveTicketButton, java.awt.BorderLayout.CENTER);

        menuButtons.add(reserve);

        tickets.setLayout(new java.awt.BorderLayout());

        myTicketsButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        myTicketsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myTicketsButton.setText("My Tickets");
        myTicketsButton.setPreferredSize(new java.awt.Dimension(200, 100));
        myTicketsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTicketsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myTicketsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myTicketsButtonMouseExited(evt);
            }
        });
        tickets.add(myTicketsButton, java.awt.BorderLayout.CENTER);

        menuButtons.add(tickets);

        calendar.setPreferredSize(new java.awt.Dimension(200, 100));
        calendar.setLayout(new java.awt.BorderLayout());

        calendarButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        calendarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarButton.setText("Calendar");
        calendarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calendarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calendarButtonMouseExited(evt);
            }
        });
        calendar.add(calendarButton, java.awt.BorderLayout.CENTER);

        menuButtons.add(calendar);

        javax.swing.GroupLayout menuHideLayout = new javax.swing.GroupLayout(menuHide);
        menuHide.setLayout(menuHideLayout);
        menuHideLayout.setHorizontalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuHideLayout.setVerticalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        Menu.add(menuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new javax.swing.OverlayLayout(Body));

        jLayeredPane1.setBackground(new java.awt.Color(51, 255, 204));

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome \"Name\" !");

        welcomeLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel1.setText("Click the side menu to start reserving your tickets!");

        welcomeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Railway/images/istockphoto-457433171-612x612.jpg"))); // NOI18N

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        shadowPanel.setBackground(new java.awt.Color(255, 255, 255));
        shadowPanel.setPreferredSize(new java.awt.Dimension(775, 548));

        javax.swing.GroupLayout shadowPanelLayout = new javax.swing.GroupLayout(shadowPanel);
        shadowPanel.setLayout(shadowPanelLayout);
        shadowPanelLayout.setHorizontalGroup(
            shadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        shadowPanelLayout.setVerticalGroup(
            shadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        reserveTicketPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Reserve Ticket");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        reserveButton.setText("Reserve");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No of Tickets");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Total");

        txtDate.setDateFormatString("dd-MM-yyyy");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Price");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Train name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Train no");

        txtDestination.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Destination:");

        txtStartPlace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Start Place:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Account Tag:");

        txtPass.setBackground(new java.awt.Color(153, 153, 153));
        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPass.setText("number");
        txtPass.setOpaque(true);

        jLabel19.setText("* Once searched choose date and enter number of tickets and press enter when the number of tickets entered");

        txtPrice.setBackground(new java.awt.Color(204, 102, 255));
        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTrainNo.setBackground(new java.awt.Color(204, 102, 255));
        txtTrainNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTrainNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTrainName.setBackground(new java.awt.Color(204, 102, 255));
        txtTrainName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTrainName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTotal.setBackground(new java.awt.Color(204, 102, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("*Press the search button when you've got you destination and start place");

        txtNumTickets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumTicketsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTicketsKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout reserveTicketPanelLayout = new javax.swing.GroupLayout(reserveTicketPanel);
        reserveTicketPanel.setLayout(reserveTicketPanelLayout);
        reserveTicketPanelLayout.setHorizontalGroup(
            reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel19))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStartPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTrainName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addComponent(txtTrainNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel8)))
                        .addGap(36, 36, 36)
                        .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumTickets)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        reserveTicketPanelLayout.setVerticalGroup(
            reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addComponent(txtStartPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtTrainNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addGap(14, 14, 14)
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(reserveTicketPanelLayout.createSequentialGroup()
                                .addGroup(reserveTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNumTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel10))
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reserveTicketPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        myTicketsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("My Tickets");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number:", "Train Number:", "Train Name:", "Start Place:", "Destination:", "Tickets:", "Total Price:", "Date:"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }

    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout myTicketsPanelLayout = new javax.swing.GroupLayout(myTicketsPanel);
    myTicketsPanel.setLayout(myTicketsPanelLayout);
    myTicketsPanelLayout.setHorizontalGroup(
        myTicketsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myTicketsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
            .addContainerGap())
    );
    myTicketsPanelLayout.setVerticalGroup(
        myTicketsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(myTicketsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
    );

    calendarPanel.setBackground(new java.awt.Color(255, 255, 255));

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setText("Calendar");

    javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
    calendarPanel.setLayout(calendarPanelLayout);
    calendarPanelLayout.setHorizontalGroup(
        calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(calendarPanelLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
    );
    calendarPanelLayout.setVerticalGroup(
        calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(calendarPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addContainerGap())
    );

    profilePanel.setBackground(new java.awt.Color(255, 255, 255));

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel15.setText("Profile");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel2.setText("Name:");

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel11.setText("Username:");

    jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel16.setText("Date of Birth:");

    jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel17.setText("Email:");

    jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel18.setText("Number:");

    nameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    nameLabel.setText("EMPTY");

    usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    usernameLabel.setText("EMPTY");

    dobLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    dobLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    dobLabel.setText("EMPTY");

    numberLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    numberLabel.setText("EMPTY");

    emailLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    emailLabel.setText("EMPTY");

    javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
    profilePanel.setLayout(profilePanelLayout);
    profilePanelLayout.setHorizontalGroup(
        profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(profilePanelLayout.createSequentialGroup()
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel11)
                        .addComponent(jLabel2)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addGap(18, 18, 18)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameLabel)
                        .addComponent(usernameLabel)
                        .addComponent(dobLabel)
                        .addComponent(numberLabel)
                        .addComponent(emailLabel))))
            .addContainerGap(171, Short.MAX_VALUE))
    );
    profilePanelLayout.setVerticalGroup(
        profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(profilePanelLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(53, 53, 53)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(nameLabel))
            .addGap(18, 18, 18)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usernameLabel)
                .addComponent(jLabel11))
            .addGap(27, 27, 27)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(dobLabel))
            .addGap(22, 22, 22)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailLabel))
            .addGap(22, 22, 22)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numberLabel))
            .addContainerGap(129, Short.MAX_VALUE))
    );

    jLayeredPane1.setLayer(welcomePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(shadowPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(reserveTicketPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(myTicketsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(calendarPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(profilePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(reserveTicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE)))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myTicketsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 239, Short.MAX_VALUE)))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shadowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE)))
    );
    jLayeredPane1Layout.setVerticalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reserveTicketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myTicketsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shadowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    Body.add(jLayeredPane1);

    getContentPane().add(Body, java.awt.BorderLayout.CENTER);

    setSize(new java.awt.Dimension(1045, 598));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

// function to generate a random string of length n 
    static String getNumericString(int n) {

        // chose a Character random from this String 
        String NumericString = "0123456789";

        // create StringBuffer size of AlphaNumericString 
        StringBuilder sb = new StringBuilder(n);

        for (int i = 0; i < n; i++) {

            // generate a random number between 
            // 0 to AlphaNumericString variable length 
            int index
                    = (int) (NumericString.length()
                    * Math.random());

            // add Character one by one in end of sb 
            sb.append(NumericString
                    .charAt(index));
        }

        return sb.toString();
    }

    public void changeColour(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void clickMenu(JPanel h1, boolean numberBool) {
        if (numberBool) {
            h1.setBackground(new Color(204, 204, 204));
        } else {
            h1.setBackground(new Color(102, 102, 102));
        }
    }

    public void changeImage(JLabel button, String resource) {
        ImageIcon aimg = new ImageIcon(getClass().getResource(resource));
        button.setIcon(aimg);
    }

    public void hideShow(JPanel menuShow, boolean dashBoard, JLabel button) {
        if (!dashBoard) {
            menuShow.setPreferredSize(new Dimension(50, menuShow.getHeight()));
            changeImage(button, "/Railway/images/menu_32px.png");
        } else {
            menuShow.setPreferredSize(new Dimension(270, menuShow.getHeight()));
            changeImage(button, "/Railway/images/back_32px.png");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    public void refreshMenu(JPanel h1, boolean b1) {
        if (h1 == hideMenu && b1) {
            boolUser = false;
            boolHome = false;
            clickMenu(user, boolUser);
            clickMenu(home, boolHome);
        } else if (h1 == home && b1) {
            boolMenu = false;
            boolUser = false;
            clickMenu(user, boolUser);
            clickMenu(hideMenu, boolMenu);
            hideShow(Menu, boolMenu, buttonhidemenu);
            shadowPanel.setVisible(boolMenu);
        } else if (h1 == user && b1) {
            boolMenu = false;
            boolHome = false;
            clickMenu(hideMenu, boolMenu);
            clickMenu(home, boolHome);
            hideShow(Menu, boolMenu, buttonhidemenu);
            shadowPanel.setVisible(boolMenu);

        } else {
            boolMenu = false;
            boolHome = false;
            boolUser = false;
            clickMenu(user, boolUser);
            clickMenu(hideMenu, boolMenu);
            clickMenu(home, boolHome);
            hideShow(Menu, boolMenu, buttonhidemenu);
            shadowPanel.setVisible(boolMenu);
        }
    }

    public void menuBlind(boolean boolClick) {
        welcomePanel.setVisible(!boolClick);
        reserveTicketPanel.setVisible(false);
        myTicketsPanel.setVisible(false);
        calendarPanel.setVisible(false);
        profilePanel.setVisible(false);
        shadowPanel.setVisible(boolClick);
    }

    public void visibility(JPanel h1, boolean b1) {

        if (h1 == reserveTicketPanel && b1) {
            boolUser = false;
            boolHome = false;
            boolMyTickets = false;
            boolCalendar = false;
            boolMenu = false;
            boolHome = false;
            reserveTicketPanel.setVisible(boolReserve);
            myTicketsPanel.setVisible(boolMyTickets);
            calendarPanel.setVisible(boolCalendar);
            profilePanel.setVisible(boolUser);
            welcomePanel.setVisible(boolHome);
        } else if (h1 == profilePanel && b1) {
            boolReserve = false;
            boolHome = false;
            boolMyTickets = false;
            boolCalendar = false;
            boolMenu = false;
            boolHome = false;
            reserveTicketPanel.setVisible(boolReserve);
            myTicketsPanel.setVisible(boolMyTickets);
            calendarPanel.setVisible(boolCalendar);
            profilePanel.setVisible(boolUser);
            welcomePanel.setVisible(boolHome);
        } else if (h1 == myTicketsPanel && b1) {
            boolUser = false;
            boolHome = false;
            boolReserve = false;
            boolCalendar = false;
            boolMenu = false;
            reserveTicketPanel.setVisible(boolReserve);
            myTicketsPanel.setVisible(boolMyTickets);
            calendarPanel.setVisible(boolCalendar);
            profilePanel.setVisible(boolUser);
            welcomePanel.setVisible(boolHome);
        } else if (h1 == calendarPanel && b1) {
            boolUser = false;
            boolHome = false;
            boolMyTickets = false;
            boolReserve = false;
            boolMenu = false;
            reserveTicketPanel.setVisible(boolReserve);
            myTicketsPanel.setVisible(boolMyTickets);
            calendarPanel.setVisible(boolCalendar);
            profilePanel.setVisible(boolUser);
            welcomePanel.setVisible(boolHome);
        } else {
            welcomePanel.setVisible(true);
            boolUser = false;
            boolHome = false;
            boolCalendar = false;
            boolMyTickets = false;
            boolReserve = false;
            boolMenu = false;
            calendarPanel.setVisible(boolCalendar);
            reserveTicketPanel.setVisible(boolReserve);
            myTicketsPanel.setVisible(boolMyTickets);
            calendarPanel.setVisible(boolCalendar);
            profilePanel.setVisible(boolUser);
        }
    }

    public void setProfile() {
        nameLabel.setText(fullname);
        usernameLabel.setText(username);
        emailLabel.setText(email);
        dobLabel.setText(dob);
        numberLabel.setText(number);
        welcomeLabel.setText("Welcome " + fullname + " !");
        txtPass.setText(id);
        idLabel.setText(" Account ID Tag: " + id);
    }

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway", "root", "");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadStartPlace() {

        try {
            pst = con.prepareStatement("SELECT DISTINCT startplace FROM traindetails");
            rs = pst.executeQuery();
            txtStartPlace.removeAllItems();

            while (rs.next()) {

                txtStartPlace.addItem(rs.getString(1));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void LoadDestination() {

        try {
            pst = con.prepareStatement("SELECT DISTINCT destination FROM traindetails");
            rs = pst.executeQuery();
            txtDestination.removeAllItems();

            while (rs.next()) {
                txtDestination.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean verifyFields() {
        String nTickets = txtNumTickets.getText();
        String ticketTotal = String.valueOf(txtTotal.getText());
        
        if (nTickets.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The number of tickets is not entered", "Empty fields", 2);
            return false;
        } else if (ticketTotal.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Total is not filled", "Empty fields", 2);
            return false;          
        }
        else {
            return true;
        }
    }

    public void load() {
        String splace = txtStartPlace.getSelectedItem().toString();
        String dplace = txtDestination.getSelectedItem().toString();
        try {
            pst = con.prepareStatement("SELECT * FROM traindetails where startplace = ? and destination = ?");
            pst.setString(1, splace);
            pst.setString(2, dplace);
            rs = pst.executeQuery();

            if (rs.next() == true) {
                txtTrainNo.setText(rs.getString("tno"));
                txtTrainName.setText(rs.getString("tname"));
                txtPrice.setText("£" + String.valueOf(new DecimalFormat("0.00").format(rs.getDouble("price"))));
                txtNumTickets.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Record not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getMyTicketsDetails() {
        try {
            pst = con.prepareStatement("select * from reservation");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c = rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                if (rs.getString("pno").equals(id)) {
                    for (int i = 0; i <= c; i++) {
                        v.add(rs.getString("ticketnum"));
                        v.add(rs.getString("tno"));
                        v.add(rs.getString("tname"));
                        v.add(rs.getString("splace"));
                        v.add(rs.getString("dplace"));
                        v.add(rs.getString("ticket"));
                        v.add("£"+ rs.getString("total"));
                        v.add(rs.getString("date"));
                    }
                    d.addRow(v);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(addTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changeColour(buttonClose, new Color(255, 24, 0));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changeColour(buttonClose, new Color(102, 102, 102));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
        boolMenu = !boolMenu;
        clickMenu(hideMenu, boolMenu);
        refreshMenu(hideMenu, boolMenu);
        menuBlind(boolMenu);
        if (boolMenu) {
            hideShow(Menu, boolMenu, buttonhidemenu);
        } else {
            hideShow(Menu, boolMenu, buttonhidemenu);
        }
        if (!boolMenu) {
            homeButtonMouseClicked(null);
            visibility(welcomePanel, boolHome);
        }
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        changeColour(lineHideMenu, new Color(255, 102, 0));
        changeColour(lineUser, new Color(255, 102, 0));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        changeColour(lineHideMenu, new Color(102, 102, 102));
        changeColour(lineUser, new Color(102, 102, 102));
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        boolHome = true;
        clickMenu(home, boolHome);
        refreshMenu(home, boolHome);
        visibility(welcomePanel, boolHome);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        changeColour(lineHome, new Color(102, 102, 102));
        changeColour(nextLine, new Color(102, 102, 102));
    }//GEN-LAST:event_homeButtonMouseExited

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        changeColour(lineHome, new Color(255, 102, 0));
        changeColour(nextLine, new Color(255, 102, 0));
    }//GEN-LAST:event_homeButtonMouseEntered

    private void userButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseClicked
        boolUser = !boolUser;
        clickMenu(user, boolUser);
        refreshMenu(user, boolUser);
        visibility(profilePanel, boolUser);
    }//GEN-LAST:event_userButtonMouseClicked

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        changeColour(lineUser, new Color(255, 102, 0));
        changeColour(lineHome, new Color(255, 102, 0));
    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        changeColour(lineUser, new Color(102, 102, 102));
        changeColour(lineHome, new Color(102, 102, 102));
    }//GEN-LAST:event_userButtonMouseExited

    private void reserveTicketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveTicketButtonMouseClicked
        boolReserve = !boolReserve;
        refreshMenu(reserve, boolOther);
        visibility(reserveTicketPanel, boolReserve);
        Calendar cal = Calendar.getInstance();
        java.util.Date date = cal.getTime();
        txtDate.setDate(date);
    }//GEN-LAST:event_reserveTicketButtonMouseClicked

    private void myTicketsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTicketsButtonMouseClicked
        boolMyTickets = !boolMyTickets;
        refreshMenu(tickets, boolOther);
        visibility(myTicketsPanel, boolMyTickets);
    }//GEN-LAST:event_myTicketsButtonMouseClicked

    private void calendarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseClicked
        boolCalendar = !boolCalendar;
        refreshMenu(calendar, boolOther);
        visibility(calendarPanel, boolCalendar);
    }//GEN-LAST:event_calendarButtonMouseClicked

    private void reserveTicketButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveTicketButtonMouseEntered
        reserveTicketButton.setForeground(Color.white);
        reserve.setBackground(Color.black);
    }//GEN-LAST:event_reserveTicketButtonMouseEntered

    private void reserveTicketButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveTicketButtonMouseExited
        reserveTicketButton.setForeground(Color.black);
        reserve.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_reserveTicketButtonMouseExited

    private void myTicketsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTicketsButtonMouseEntered
        myTicketsButton.setForeground(Color.white);
        tickets.setBackground(Color.black);
    }//GEN-LAST:event_myTicketsButtonMouseEntered

    private void myTicketsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTicketsButtonMouseExited
        myTicketsButton.setForeground(Color.black);
        tickets.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_myTicketsButtonMouseExited

    private void calendarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseEntered
        calendarButton.setForeground(Color.white);
        calendar.setBackground(Color.black);
    }//GEN-LAST:event_calendarButtonMouseEntered

    private void calendarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseExited
        calendarButton.setForeground(Color.black);
        calendar.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_calendarButtonMouseExited

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        String pno = txtPass.getText();
        String ticketUN = getNumericString(8);
        String start = txtStartPlace.getSelectedItem().toString();
        String finish = txtDestination.getSelectedItem().toString();
        String tno = txtTrainNo.getText();
        String tname = txtTrainName.getText();
        String price = txtPrice.getText().substring(1);
        SimpleDateFormat date_form = new SimpleDateFormat("dd-mm-yyyy");
        String date = date_form.format(txtDate.getDate());
        String tickets = txtNumTickets.getText();
        String total = txtTotal.getText().substring(1);

        if (verifyFields()) {
            try {
                pst = con.prepareStatement("INSERT INTO `reservation`(`pno`, `ticketnum`, `splace`, `dplace`, `tno`, `tname`, `price`, `date`, `ticket`, `total`) VALUES (?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, pno);
                pst.setString(2, ticketUN);
                pst.setString(3, start);
                pst.setString(4, finish);
                pst.setString(5, tno);
                pst.setString(6, tname);
                pst.setString(7, price);
                pst.setString(8, date);
                pst.setString(9, tickets);
                pst.setString(10, total);
                int k = pst.executeUpdate();

                if (k == 1) {
                    JOptionPane.showMessageDialog(this, "Record Added");
                    txtTrainNo.setText("");
                    txtTrainName.setText("");
                    txtPrice.setText("");
                    txtNumTickets.setText("");
                    txtTotal.setText("");
                    reserveButton.setEnabled(false);
                    txtNumTickets.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Record Failed");
                }
            } catch (SQLException ex) {
                Logger.getLogger(addTrain.class.getName()).log(Level.SEVERE, null, ex);
            }
            getMyTicketsDetails();
        }
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked


    }//GEN-LAST:event_jTable1MouseClicked

    private void txtNumTicketsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTicketsKeyTyped
        //Only allow numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumTicketsKeyTyped

    private void txtNumTicketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTicketsKeyPressed
        double price, numOfTickets, total;
        
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            price = Double.parseDouble(txtPrice.getText().substring(1));

            numOfTickets = Double.parseDouble(txtNumTickets.getText());
            total = price * numOfTickets;
            
            txtTotal.setText("£" + String.valueOf(new DecimalFormat("0.00").format(total)));
            reserveButton.setEnabled(true);
        }
    }//GEN-LAST:event_txtNumTicketsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel accountN;
    private javax.swing.JPanel buttonClose;
    private javax.swing.JPanel buttonMax;
    private javax.swing.JPanel buttonMin;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JPanel calendar;
    private javax.swing.JLabel calendarButton;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel iconMinMaxClose;
    private javax.swing.JLabel idLabel;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel lineHideMenu;
    private javax.swing.JPanel lineHome;
    private javax.swing.JPanel lineUser;
    private javax.swing.JPanel menuButtons;
    private javax.swing.JPanel menuHide;
    private javax.swing.JLabel myTicketsButton;
    private javax.swing.JPanel myTicketsPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel nextLine;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel reserve;
    private javax.swing.JButton reserveButton;
    private javax.swing.JLabel reserveTicketButton;
    private javax.swing.JPanel reserveTicketPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel shadowPanel;
    private javax.swing.JPanel tickets;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JComboBox<String> txtDestination;
    private javax.swing.JTextField txtNumTickets;
    private javax.swing.JLabel txtPass;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JComboBox<String> txtStartPlace;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTrainName;
    private javax.swing.JLabel txtTrainNo;
    private javax.swing.JPanel user;
    private javax.swing.JLabel userButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeImage;
    public javax.swing.JLabel welcomeLabel;
    public javax.swing.JLabel welcomeLabel1;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
